# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'studentTrips' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for studentTrips

  target 'studentTrips-tvOS' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for studentTrips-tvOS

    target 'studentTrips-tvOSTests' do
      inherit! :search_paths
      # Pods for testing
      pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

    end

  end

  target 'studentTripsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

  
